# 数列の種別を表す定数を定義したクラス
class ProgressionType

  # 等差数列
  ARITHMETIC_PROGRESSION = 0
  ARITHMETIC_PROGRESSION.freeze

  # 等比数列
  GEOMETRIC_PROGRESSION = 1
  GEOMETRIC_PROGRESSION.freeze

  # 階差数列を1つ持つ数列
  PROGRESSION_WITH_1_DIFFERENCE_PROGRESSION = 2
  PROGRESSION_WITH_1_DIFFERENCE_PROGRESSION.freeze

  # 階差数列を1つ持つ数列
  PROGRESSION_WITH_2_DIFFERENCE_PROGRESSIONS = 3
  PROGRESSION_WITH_2_DIFFERENCE_PROGRESSIONS.freeze

  # フィボナッチ数列
  FIBONACCI_PROGRESSION = 4
  FIBONACCI_PROGRESSION.freeze

  # トリボナッチ数列
  TRIBONACCI_PROGRESSION = 5
  TRIBONACCI_PROGRESSION.freeze
end
